
require 'aphid/rake'

PROJECT_NAME         = "New Application" # TODO Replace this with Erb
ROOT_PATH            = File.expand_path(File.dirname(__FILE__))
DEFAULT_TASKS        = [ :build ]
WATCH_TASKS          = DEFAULT_TASKS
WATCH_SOURCE_TASKS   = DEFAULT_TASKS
SOURCE_FILES         = [ "Application/Application.js" ]
DOCUMENTATION_SOURCE = "Application/Application.js"
STYLESHEET_FILES     = [ "Resources/Stylesheets/Application.less" ]
