#!/usr/bin/env ruby

require 'rubygems'
begin
  require 'commander/import'
rescue LoadError
  puts "\nYou'll need the Commander gem to run this command. Simply run:\n\n"
  puts "  $ gem install commander"
  puts "\nand you should be all set!\n\n"
  exit
end

APHID_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

require File.join(File.dirname(__FILE__), 'lib', 'aphid', 'bootstrapper')

# :name is optional, otherwise uses the basename of this executable
program :name, "Aphid Bootstrapper"
program :version, File.read("#{APHID_ROOT}/VERSION").strip
program :description, 'Aphid'

default_command :help

command :new do |c|
  c.syntax = 'aphid new [name] [options]'
  c.description = 'Initializes [name] as a new Aphid project.'
  c.option "--[no-]git", "Initialize the project as a Git repository (default: true)"
  c.option "--[no-]vendorize", "Copy Aphid to or initialize as a submodule in Vendor (default: false)"
  c.action do |args, options|
    if args.first.nil?
      command(:help).call(["new"])
      exit
    end
    options.default :git => true

    Aphid::Bootstrapper.new(args.first) do |aphid|
      aphid.bootstrap!
      aphid.initialize_git_repository if options.git
      aphid.vendorize_aphid if options.vendorize
      aphid.build_project
    end
  end
end
  end
end
