#!/usr/bin/env ruby

require "rubygems"
begin
  require "commander/import"
rescue LoadError
  puts "\nYou'll need the Commander gem to run this command. Simply run:\n\n"
  puts "  $ gem install commander"
  puts "\nand you should be all set!\n\n"
  exit
end

require File.join(File.dirname(__FILE__), 'lib', 'aphid', 'bootstrapper')

# :name is optional, otherwise uses the basename of this executable
program :name, "Aphid Bootstrapper"
program :version, Aphid.version
program :description, "Aphid"

default_command :help

command :new do |c|
  c.syntax = "aphid new [name] [options]"
  c.description = 'Initializes [name] as a new Aphid project.'
  c.option "--[no-]git", "Initialize the project as a Git repository (default: true)"
  c.option "--[no-]vendorize", "Copy Aphid to or initialize as a submodule in Vendor (default: false)"
  c.action do |args, options|
    if args.first.nil?
      command(:help).call(["new"])
      exit
    end
    options.default :git => true

    Aphid::Bootstrapper.new(args.first) do |aphid|
      aphid.bootstrap!
      aphid.initialize_git_repository if options.git
      aphid.vendorize_aphid if options.vendorize
      aphid.build_project
    end
  end
end

command :vendorize do |c|
  c.syntax = "aphid vendorize [options]"
  c.description = "Copies Aphid or initializes it as a submodule in Vendor. This must be run from the root path of an Aphid-based project."
  c.summary = "Places Aphid in the Vendor folder"
  c.option "--force", "Forces the vendorization of Aphid, overwriting the previous copy (default: false)"
  c.option "--[no-]submodule", "Adds Aphid as a Git submodule (default: true, if a valid Git repository)"
  c.action do |args, options|
    begin
      raise unless File.read("Rakefile").lines.grep(/require.*aphid\/rake/).length > 0
    rescue
      puts
      puts "ERROR: You must run \"aphid vendorize\" from the root of your Aphid-based project"
      puts
      exit
    end
    begin
      options.default :force => false, :submodule => true
      Aphid::Bootstrapper.new(Dir.getwd) do |aphid|
        aphid.vendorize_aphid options
      end
    rescue Aphid::AlreadyVendoredError
      puts
      puts "Error: Aphid already exists in Vendor. Try with --force to replace this version."
      puts
      exit
    end
  end
end

command :path do |c|
  c.syntax = "aphid path"
  c.description = "Returns the path to the active Aphid installation"
  c.action do |args, options|
    puts Aphid.path
  end
end
